server:
  port: ${SERVER_PORT:8081}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    drop-first: true

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_HOST_NAME:localhost:9093}

kafka:
  topics:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    application-denied: application-denied


