name: Build

on:
  pull_request:
    branches:
      - 'feature/devops'

  push:
    branches:
      - 'feature/devops'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Maven Package
        run: mvn -B clean verify

      - name: Test Coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./coverage1.xml,./coverage2.xml