name: Build

on:
  pull_request:
    branches:
      - 'feature/devops'

  push:
    branches:
      - 'feature/devops'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Test Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}